/*COLOCAR O BANCO EM USO */
USE ComaBem;

/*CRIANDO UM PERFIL DE ACESSO AO BANCO*/
CREATE ROLE novoPerfilT6;

/*CRIANDO UM NOVO USUARIO E ADICIONANDO A ELE O PERFIL CRIADO*/
CREATE USER turma6 IDENTIFIED BY 'senhaBemForte' DEFAULT ROLE novoPerfilT6;

/*DEFININDO O USUARIO CRIADO PARA APENAS PODER UTILIZAR O COMANDO SELECT*/
GRANT SELECT ON ComaBem.* TO turma6;

/*APOS ABRIR O WORKBENCH COM O NOVO USUÁRIO, FAZER UM TESTE DE SELECT*/
SELECT * FROM Produtos;

/*AGORA TENTAR FAZER UMA INSERÇÃO DE DADOS, APRESENTARA ERRO PORQUE O USUARIO ESTA LIBERADO APENAS PARA REALIZAR SELECT.*/
INSERT INTO Produtos (cd_produto, ds_produto, vl_produto, cd_unidade) values ("Bolo de Cenoura", 20.00, 3, 1);